name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install server deps
        working-directory: server
        run: npm ci
      - name: Smoke test server code
        working-directory: server
        run: node -e "require('fs').accessSync('index.js')"

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install web deps
        working-directory: web
        run: npm ci
      - name: Build web
        working-directory: web
        run: npm run build